#!/bin/bash

# setup GLT500 RS485 Depth Sensor

standardPromptAndActions='yes'

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources